spring:
  datasource:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: 123456
      mybatis:
        project : src/main/java
        resources : src/main/resources
mybatis:
  type-aliases-package: com.mwx.test.mapper
  mapper-locations: classpath:mybatis/*.xml